[build]
  command = "CI= npm run build"
   publish = "dist/"
  functions = "functions"
[functions]
  node_bundler = "esbuild"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[dev]
  functions = "functions"
  publish = "public"
